// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtuzqituipiqgbbzemrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dXpxaXR1aXBpcWdiYnplbXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTQzMDYsImV4cCI6MjA2NjI3MDMwNn0.OXGPwAIi7nh2DNqLjZDrDrMr5CHM2BSzNh25BqXQUE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);